Restructuring the reactor build, Upgrading to latest Eclipse and deps
jboss-fuse/fuse-components pull request #113
Opened 2019-04-10 11:18 UTC by lhein

2019-04-11 13:38 UTC, apupier commented
CI pull request job is reporting this error:

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-readable POM /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest/camel-sap/com.sap.conn.jco/pom.xml: /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest/camel-sap/com.sap.conn.jco/pom.xml (No such file or directory) @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project  (/home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest/camel-sap/com.sap.conn.jco/pom.xml) has 1 error
[ERROR]     Non-readable POM /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest/camel-sap/com.sap.conn.jco/pom.xml: /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest/camel-sap/com.sap.conn.jco/pom.xml (No such file or directory)
```

2019-04-11 13:39 UTC, lhein commented
right....might be caused by the not up2date job config. with that PR only one call to mvn is needed in the main reactor.

2019-04-11 13:54 UTC, apupier commented on camel-sap/features/org.fusesource.camel.component.sap.feature/feature.xml
> +      <import plugin="com.sap.conn.jco" version="3.0.11.redhat_1" match="greaterOrEqual"/> <!--really? sounds weird imo -->
add comment to have a look before merging

2019-04-11 14:08 UTC, apupier submitted a review, later dismissed
- What about adding the required maven repository, even if requires vpn connection?
Otherwise I got [ERROR] Failed to execute goal on project camel-sap: Could not resolve dependencies for project org.fusesource.components.camel-sap:camel-sap:bundle:6.3.0.redhat-SNAPSHOT: The following artifacts could not be resolved: com.sap.conn.jco:sapjco3:jar:3.0.11, com.sap.conn.idoc:sapidoc3:jar:3.0.10: Could not find artifact com.sap.conn.jco:sapjco3:jar:3.0.11 at specified path C:\git\fuse-components\camel-sap\plugins\camel-sap-component\target\lib\sapjco3.jar -> [Help 1]

- even with artefacts locally, if I first "mvn clean" then "mvn install"
[ERROR] Failed to execute goal on project camel-sap: Could not resolve dependencies for project org.fusesource.components.camel-sap:camel-sap:bundle:6.3.0.redhat-SNAPSHOT: The following artifacts could not be resolved: com.sap.conn.jco:sapjco3:jar:3.0.11, com.sap.conn.idoc:sapidoc3:jar:3.0.10: Could not find artifact com.sap.conn.jco:sapjco3:jar:3.0.11 at specified path C:\git\fuse-components\camel-sap\plugins\camel-sap-component\target\lib\sapjco3.jar -> [Help 1]


I think the first action is to create a job on CI to build the PR/branch to be able to start reviewing the PR in good condition.

2019-04-12 08:12 UTC, apupier commented
I created the PR job for the new structure https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fuse-components-camel-sap-6-3-x-pullrequest-new-structure

it is reproducing the same build failure that I observed locally:

```
[ERROR] Failed to execute goal on project camel-sap: Could not resolve dependencies for project org.fusesource.components.camel-sap:camel-sap:bundle:6.3.0.redhat-SNAPSHOT: The following artifacts could not be resolved: com.sap.conn.jco:sapjco3:jar:3.0.11, com.sap.conn.idoc:sapidoc3:jar:3.0.10: Could not find artifact com.sap.conn.jco:sapjco3:jar:3.0.11 at specified path /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest-new-structure/camel-sap/plugins/camel-sap-component/target/lib/sapjco3.jar -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project camel-sap: Could not resolve dependencies for project org.fusesource.components.camel-sap:camel-sap:bundle:6.3.0.redhat-SNAPSHOT: The following artifacts could not be resolved: com.sap.conn.jco:sapjco3:jar:3.0.11, com.sap.conn.idoc:sapidoc3:jar:3.0.10: Could not find artifact com.sap.conn.jco:sapjco3:jar:3.0.11 at specified path /home/****/workspace/fuse-components-camel-sap-6-3-x-pullrequest-new-structure/camel-sap/plugins/camel-sap-component/target/lib/sapjco3.jar
```

2019-04-15 13:52 UTC, apupier commented
tests are now failing with error:

`JCo initialization failed with java.lang.ExceptionInInitializerError: Illegal JCo archive "sapjco3-3.0.11.jar". It is not allowed to rename or repackage the original archive "sapjco3.jar".`

2019-04-16 08:57 UTC, apupier requested changes
- the plugin test are not played see https://fusesource-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/fuse-components-camel-sap-6-3-x-pullrequest-new-structure/9/testReport/org.fusesource.camel.component.sap/ which is not containing TRFCTest for instance
- would worth checking with productization team how to handle the new plugins that are now part of the built artefact (have a profile to not build them? have a rule in productization to ignore them?)

2019-04-16 08:57 UTC, apupier commented on camel-sap/tests/org.fusesource.camel.component.sap.test/pom.xml
> -            <scope>system</scope>
are you sure that we can remove the scope item? it means that we can't publish the org.fusesource.camel.component.sap.test plugin to a public location (but I guess it is already the case?)

2019-04-16 08:57 UTC, apupier commented on camel-sap/features/pom.xml
> + Copyright 2013 Red Hat, Inc.
2013 -> 2019 ?

2019-04-16 08:57 UTC, apupier commented on camel-sap/features/org.fusesource.camel.component.sap.feature/pom.xml
> + Copyright 2013 Red Hat, Inc.
2013 -> 2019?

2019-04-16 08:57 UTC, apupier commented on camel-sap/features/org.fusesource.camel.component.sap.feature/pom.xml
> +				<artifactId>ianal-maven-plugin</artifactId>
is the license file a requirement for productization? If yes, maybe we can't just skip it.

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +		<url>http://www.redhat.com</url>
http://www.redhat.com -> https://www.redhat.com

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +		<maven>3.6</maven>
I'm wondering if it is compatible with productization requirements for 6.3 stream. Worth checking.

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
>  		<camel-version>2.17.0.redhat-630133</camel-version>
this version is quite strange but not the scope of this PR (just a note for later)

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +		<jaxb.core.version>2.3.0.1</jaxb.core.version>
on 6.3 stream it was 2.2.11, I think it is something that needs to stay aligned with other Fuse dependencies

https://github.com/jboss-fuse/fuse-components/blob/94a5d126f71d7b9158210dd7c2248a345e4d428e/camel-sap/pom.xml#L181

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +		<maven.compiler.target>1.8</maven.compiler.target>
i think that in 6.3 stream we need to stick with 1.7 as it is a supported java version https://access.redhat.com/articles/310603#Red-Hat-JBoss-Fuse-63

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +		<emf.edit.version>2.14.0</emf.edit.version>
from 2.8.0 to 2.14.0, seems a big increase for a release patch stream https://github.com/jboss-fuse/fuse-components/blob/94a5d126f71d7b9158210dd7c2248a345e4d428e/camel-sap/pom.xml#L126

I think it is used at runtime too, not only for SAP Tooling. If only SAP tooling, i think it is fine. If at runtime, I think it is not but worth checking with Productization team.

2019-04-16 08:57 UTC, apupier commented on camel-sap/pom.xml
> +						<argLine>${tycho.testArgLine} -XX:+HeapDumpOnOutOfMemoryError ${platformSystemProperties} ${systemProperties} ${moduleProperties} -Dusage_reporting_enabled=false -Dorg.jboss.tools.vpe.loadxulru
why do we need all these parameters?
As far as I know
- groovy.grape and ivy.message.logger.level is used by Fuse Tooling
- usage_reporting_enabled is used by Jboss Tools
- org.jboss.tools.vpe.loadxulrunner given the name it seems to be used by Jboss Tools only also

2019-04-16 08:57 UTC, apupier commented on camel-sap/tests/pom.xml
> + Copyright 2013 Red Hat, Inc.
2013 -> 2019

2019-05-08 11:15 UTC, lhein commented
Priority of that task has been lowered and work is paused now.

2021-05-20 10:53 UTC, closed without merging